### ISSUE TITLE
Icons don't show

### ISSUE THREAD

**Issue by L0rz** [kirstenhh/nc-bpm-app#10]
I have a new Nextcloud AIO instance, and after teh installation of the Plug in the Icons to save and download are not shown.

![image](https://github.com/user-attachments/assets/193082fd-36c4-434a-a983-176ca1ae3e13)

![image](https://github.com/user-attachments/assets/6dab5ac0-b3ab-4caf-9cae-9b5e1272bc77)

**Comment by kirstenhh** [comment]
Will be fixed in the upcoming update for Nextcloud v30 in the next couple of weeks

**Comment by kirstenhh** [comment]
I haven't heard back from you and I'm reasonably sure that I've fixed this. If the new version gives you trouble, feel free to open a new issue!
