### ISSUE TITLE
App cannot be updated

### ISSUE THREAD

**Issue by Nils98Ar** [kirstenhh/nc-bpm-app#3]
The URL seems to be wrong.

GuzzleHttp\Exception\ClientException: Client error: `GET https://github.com/kirstenhh/nc-bpm-app/releases/download/v1.1.0/files_bpm-v1.1.0.tar.gz` resulted in a `404 Not Found` response: Not Found

**Comment by ivosm** [comment]
+1

**Comment by C0FFEEC0FFEE** [comment]
+2

**Comment by flovl** [comment]
+3

**Comment by thiemel** [comment]
++
(=4)

**Comment by kurb70** [comment]
+1

**Comment by gyarakilaszlo** [comment]
+1

**Comment by kirstenhh** [comment]
Sorry all, it looks like I somehow marked the release as a draft after having published it (I'm still not sure how that happened) and didn't notice. It should be fixed now.

**Comment by Nils98Ar** [comment]
@kirstenhh Thank you!
