### ISSUE TITLE
Feature: color-picker in BPMN editor

### ISSUE THREAD

**Issue by brafreider** [kirstenhh/nc-bpm-app#7]
as the BPMN editor bundled with the NC extension already supports element colors from within BPMN-Files, it would be great to have a color picker within the element-options of the editor to be able to color elements.

There is a BPMN extension that adds this functionality. It can be found on https://github.com/bpmn-io/bpmn-js-color-picker

The official BPMN demo on https://demo.bpmn.io seems to include this extension too.

**Comment by kirstenhh** [comment]
Added in the latest release!
