### ISSUE TITLE
Editing not working as normal user NC 28.0.3

### ISSUE THREAD

**Issue by 64738648732** [kirstenhh/nc-bpm-app#9]
Hello,

First of all, many thanks for the great app.

In Nextcloud 28.0.3 the creation of new bpmn files works without any problems. However, when you open it again, the file is not loaded. I could find the following error:

https://XXX/index.php/apps/files_bpm/page/getFileInfo?fileId=49652

{   "message": "Der angemeldete Benutzer muss ein Administrator sein". }

If I use an admin account, I can edit the file without any problems. However, all users should be able to edit the file, especially if they have created the file themselves.

Thanks!

Best regards,

Alex

**Comment by kirstenhh** [comment]
New update up that (I hope and pray) fixes this issue, please let me know if you're successful with the newest version!

**Comment by 64738648732** [comment]
Sorry for the late answer. Now it is working. Thank you!

**Comment by 64738648732** [comment]
Fixed

**Comment by 64738648732** [comment]
fixed
